export default function Footer() {
  return (
    <footer className="max-w-7xl mx-auto px-4 py-8 mt-16 border-t border-slate-200/60 text-center text-xs text-slate-400">
      Created by Gabriel Sherman &middot; Scores generated by AI &middot; Data is approximate and for exploratory purposes
    </footer>
  );
}
