export default function Footer() {
  return (
    <footer className="max-w-[1400px] mx-auto px-4 sm:px-6 mt-16">
      <div className="pt-6 border-t border-slate-200/60 pb-8 text-center text-xs text-slate-400">
        Created by Gabriel Sherman &middot; Scores generated by AI &middot; Data is approximate and for exploratory purposes
        <div className="mt-1 text-slate-300">v3-touch</div>
      </div>
    </footer>
  );
}
